activity/urls.py
from django.urls import include, path
from .views import *

urlpatterns = [
    path("add/<int:activity_id>", add_activity, name="add_activity")
]

api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from rest_framework.routers import DefaultRouter, SimpleRouter

from .auth_views import *
from .views import OperationsViewSet

router = DefaultRouter()
router.register(r'authentication', User_Accounts, basename='User Accounts')
router.register(r'operations', viewset=OperationsViewSet, basename="ops")

urlpatterns = [
    path("", include(router.urls)),
]

cpsam/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),
    
    path('auth/', include("authentication.urls")),
    path('api/', include("api.urls")),
    path('activity/', include("activity.urls")),
    
    path('', view=dashboard, name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from authentication.models import SiteUser
import re


# Utility Classes
class GenericAchievement(models.Model):
    # certificate = models.ForeignKey("core.Filelog", on_delete=models.CASCADE, related_name="%(class)s_certificate")
    # support_docs = models.ForeignKey("core.Filelog", on_delete=models.SET_NULL, null=True, related_name="%(class)s_support_docs")
    certificate = models.FileField(upload_to='student_certificates/', null=True)
    brochures = models.FileField(upload_to='event_brochures/', null=True)
    participation_photos = models.FileField(upload_to='participation_photos/', null=True)
    event_id = models.FileField(upload_to='event_id_photos', null=True)
    team = models.ForeignKey("core.Team", on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField("core.Tags", null=True, blank=True)
    
    created_by = models.ForeignKey(SiteUser, on_delete=models.CASCADE, related_name="%(class)s_createdby", null=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    approved_by = models.ForeignKey(SiteUser, on_delete=models.SET_NULL, related_name="%(class)s_approver", null=True, blank=True)
    approval_timestamp = models.DateTimeField(blank=True, null=True)
    domain = models.ForeignKey("core.Domain", on_delete=models.RESTRICT)
    
    class Meta:
        abstract = True
    
class BaseAchievement(GenericAchievement):
    title = models.CharField(max_length=100)
    institution = models.CharField(max_length=300, null=True, blank=True)
    organizer_name = models.CharField(max_length=100, help_text="Internal Sub Organization within institution", blank=True)
    from_date = models.DateField()
    to_date = models.DateField()
    class event_levels(models.TextChoices):
        INTERNATIONAL = ("INTERNATIONAL", "International")
        NATIONAL = ("NATIONAL", "National")
        STATE = ("STATE", "State")
        DISTRICT = ("DISTRICT", "District")
        ZONAL = ("ZONAL", "Zonal")
    class results(models.TextChoices):
        FIRST = ("FIRST", "First Prize")
        SECOND = ("SECOND", "Second Prize")
        THIRD = ("THIRD", "Third Prize")
        SPECIAL_MENTION = ("SPECIAL_MENTION", "Special Mention")
        PARTICIPATION = ("PARTICIPATION", "Participation")
        
    event_level = models.CharField(
        max_length=20,
        choices=event_levels.choices,
        default=event_levels.STATE,
    )
    result = models.CharField(
        max_length=20,
        choices=results.choices,
        default=results.PARTICIPATION,
        verbose_name="Achievement Outcome"
    )
                                      
    location_link = models.URLField(help_text="Event Venue Link")
    
    def __str__(self):
        return self.title
    class Meta:
        abstract = True
        
# Utility Models
class AcademicYear(models.Model):
    start_from = models.DateField()
    end_on = models.DateField()
    current = models.BooleanField()
    
    def year(self):
        return str(self.start_from.year) 
    def fullyear(self):
        return str(self.start_from.year) + "-" + str(self.end_on.year)
    
    def __str__(self):
        return "AY " + self.year()
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['current'],
                condition=models.Q(current=True),
                name='unique_true_is_active'
            )
        ]

class Course_Provider(models.Model):
    provider_name = models.CharField(max_length=200)
    provider_link = models.URLField()
    
    def __str__(self):
        return self.provider_name
    
class Recognized_Student_Body(models.Model):
    organization_name = models.CharField(max_length=100)
    organization_link = models.URLField()
    global_chapter = models.BooleanField(help_text="Is it a National/Internation Student Chapter")
    organization_strength = models.IntegerField(help_text="Approximate count of members")
    

class Domain(models.Model):
    domain_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.domain_name

class Tags(models.Model):
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    tag_name = models.CharField(max_length=100)
    normalized_tag_name = models.CharField(max_length=100, blank=True, null=True, unique=True)
    
    created_by = models.ForeignKey(SiteUser, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def normalize_string(self, s: str) -> str:
            return re.sub(r'[^a-z0-9]', '', s.lower())
        
    def save(self, *args, **kwargs):
        self.normalized_tag_name = self.normalize_string(self.tag_name)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.tag_name
    

class Team(models.Model):
    team_name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    members = models.ManyToManyField("core.TeamMember")

class TeamMember(models.Model):
    member = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    role = models.CharField(max_length=100)
    
    def __str__(self):
        return self.member.full_name
    
class FileReasons(models.Model):
    reason = models.CharField(max_length=100)
    file_size = models.IntegerField(help_text="File Size In Bytes (1MB = 1000000 Bytes)")
    
    def __str__(self):
        return self.reason

class FileLog(models.Model):
    filename = models.CharField(max_length=100)
    # reason = models.ForeignKey(FileReasons, on_delete=models.CASCADE)
    reason = models.CharField(max_length=100)
    created_by = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.filename

activity/forms.py
from django import forms
from .models import *

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True
    is_required = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result

class CompetitionForm(forms.ModelForm):
    approved_by = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    approval_timestamp = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    from_date = to_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',   # HTML5 datetime picker
            'class': 'form-control',    # optional for styling (Bootstrap/Tailwind etc.)
        }))
    institution = forms.CharField(label="Organizing Insitution", required=True)
    def clean(self):
        cleaned_data = super().clean()
        from_date = cleaned_data.get("from_date")
        to_date = cleaned_data.get("to_date")

        if from_date and to_date and from_date > to_date:
            self.add_error("from_date", "Number of days cannot be negative")

        return cleaned_data
        
    # support_docs = forms.FileField(widget=forms.HiddenInput(), required=False)
    # event_id = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # participation_photos = MultipleFileField()
    # brochures = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # certificate = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    
    
    class Meta:
        model = Competition
        fields = ['title', 'domain', 'event_level', 'institution','organizer_name','location_link', 'from_date', 'to_date', 'result', 'certificate', 'brochures', 'participation_photos', 'event_id']


class CourseForm(forms.ModelForm):
    approved_by = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    approval_timestamp = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    from_date = to_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',   # HTML5 datetime picker
            'class': 'form-control',    # optional for styling (Bootstrap/Tailwind etc.)
        }))
    def clean(self):
        cleaned_data = super().clean()
        from_date = cleaned_data.get("from_date")
        to_date = cleaned_data.get("to_date")

        if from_date and to_date and from_date > to_date:
            self.add_error("from_date", "Number of days cannot be negative")

        return cleaned_data
        
    # support_docs = forms.FileField(widget=forms.HiddenInput(), required=False)
    # event_id = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # participation_photos = MultipleFileField()
    # brochures = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # certificate = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    title = forms.CharField(label="Course Title")
    
    class Meta:
        model = Course_Completion
        # fields = ['title', 'domain', 'event_level', 'institution','organizer_name','location_link', 'from_date', 'to_date', 'result', 'certificate', 'brochures', 'participation_photos', 'event_id']
        fields = ['title', 'domain', 'institution', 'course_provider', 'from_date', 'to_date','verification_url', 'certificate']
        

class WorkshopForm(forms.ModelForm):
    approved_by = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    approval_timestamp = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    from_date = to_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',   # HTML5 datetime picker
            'class': 'form-control',    # optional for styling (Bootstrap/Tailwind etc.)
        }))
    def clean(self):
        cleaned_data = super().clean()
        from_date = cleaned_data.get("from_date")
        to_date = cleaned_data.get("to_date")

        if from_date and to_date and from_date > to_date:
            self.add_error("from_date", "Number of days cannot be negative")

        return cleaned_data
        
    # support_docs = forms.FileField(widget=forms.HiddenInput(), required=False)
    # event_id = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # participation_photos = MultipleFileField()
    # brochures = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # certificate = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # title = forms.CharField(label="Course Title")
    
    class Meta:
        model = Workshop
        fields = ['title', 'domain', 'event_level', 'institution','organizer_name','location_link', 'from_date', 'to_date', 'certificate', 'brochures', 'participation_photos', 'event_id']
        

class PPOForm(forms.ModelForm):
    approved_by = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    approval_timestamp = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    from_date = to_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',   # HTML5 datetime picker
            'class': 'form-control',    # optional for styling (Bootstrap/Tailwind etc.)
        }))
    def clean(self):
        cleaned_data = super().clean()
        from_date = cleaned_data.get("from_date")
        to_date = cleaned_data.get("to_date")

        if from_date and to_date and from_date > to_date:
            self.add_error("from_date", "Number of days cannot be negative")

        return cleaned_data
        
    # support_docs = forms.FileField(widget=forms.HiddenInput(), required=False)
    # event_id = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # participation_photos = MultipleFileField()
    # brochures = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # certificate = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # title = forms.CharField(label="Course Title")
    
    class Meta:
        model = Preplacement
        fields = ['domain', 'organization', 'ppo_type', 'role', 'from_date', 'to_date', 'location_link', 'github_link', 'certificate']
        # fields = '__all__'

class ProjectForm(forms.ModelForm):
    approved_by = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    approval_timestamp = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    from_date = to_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',   # HTML5 datetime picker
            'class': 'form-control',    # optional for styling (Bootstrap/Tailwind etc.)
        }))
    def clean(self):
        cleaned_data = super().clean()
        from_date = cleaned_data.get("from_date")
        to_date = cleaned_data.get("to_date")

        if from_date and to_date and from_date > to_date:
            self.add_error("from_date", "Number of days cannot be negative")

        return cleaned_data
        
    # support_docs = forms.FileField(widget=forms.HiddenInput(), required=False)
    # event_id = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # participation_photos = MultipleFileField()
    # brochures = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    # certificate = forms.FileField(widget=forms.ClearableFileInput(), required=True)
    title = forms.CharField(label="Project Title")
    problem_statement = forms.CharField(widget=forms.Textarea(attrs={"class": "cols-span-full"}))
    
    class Meta:
        model = Project
        fields = ['title', 'domain', 'project_type','from_date', 'to_date', 'github_link', 'problem_statement', 'prototype_video']
        # fields = '__all__'

activity/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from core.models import Tags, Domain
from authentication.models import SiteUser
from django.contrib.auth.decorators import login_required
ALL_ACTIVITIES = {
    "competition": {
        "model": Competition,
        "forms": CompetitionForm
    },
    "course completion": {
        "model": Course_Completion,
        "forms": CourseForm
    },
    "workshop/conferences": {
        "model": Workshop,
        "forms": WorkshopForm
    },
    "pre-placements": {
        "model": Preplacement,
        "forms": PPOForm
    },
    "project completion": {
        "model": Project,
        "forms": ProjectForm
    }
    
    
}

@login_required
def dashboard(request):
    return render(request, "activity/dashboard.html")

@login_required
def add_activity(request, activity_id:int):
    print(request.user.email)
    activity = ActivityManager.objects.get(id=activity_id)
    tags = Tags.objects.all()
    domains = Domain.objects.all()
    forms = ALL_ACTIVITIES.get(activity.activity_name.lower()).get("forms")
    if request.method == "POST":
        validation = forms(data=request.POST, files=request.FILES)
        if validation.is_valid():
            
            instance = validation.save(commit = False)
            instance.created_by = request.user
            instance.save()
            return redirect("home")
        else:
            forms = validation
            print(validation.errors)
    return render(request, "activity/activity_add.html", {"form":forms, "activity": activity, "tags":tags, "domains":domains})

activity/templates/activity/activity_add.html
{% extends "activity/base.html" %}

{% load static %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}
{% block title %} Add {{activity.activity_name}} {% endblock %}
{% block content %}
<div class="p-6">
<p class="text-2xl font-bold text-gray-900">Add {{activity.activity_name}}</p>
<p class="text-gray-500 mb-12">{{activity.additional_text}}</p>
<form method="POST" class="grid grid-cols-2 gap-4 activityform" enctype="multipart/form-data">
{% csrf_token %}
{{ form|crispy }}
{{ form|as_crispy_errors }}
<!-- <div class="w-full h-[1px] bg-gray-200 col-span-full"></div>
<div class="col-span-full col-start-1">
    <p class="font-semibold">Attach Support Documents</p>
    <p class="text-sm">These document will used in verifying the actuality of the proposal</p>
    <div class="flex gap-4 py-2 justify-between items-center">
        <div class="w-full">
            <label class="block mb-2 text-sm font-medium text-gray-900" for="file_input">Event ID Card</label>
            <input required accept=".jpg,.png,.PNG,.JPEG" data-reason="activity_event_ID" class="file block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" aria-describedby="file_input_help" id="file_input" type="file">
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">PNG, JPG(5MB * 1 Photo)</p>
        </div>

        <div class="w-full">
            <label class="block mb-2 text-sm font-medium text-gray-900" for="file_input">Participation photos (individual or group)</label>
            <input required multiple accept=".jpg,.png,.PNG,.JPEG" data-reason="activity_participation_photos" class="multifile block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none" aria-describedby="file_input_help" id="file_input" type="file">
            <p class="mt-1 text-sm text-gray-500" id="file_input_help">PNG, JPG(5MB * Maximum 5 Photos)</p>
        </div>

        <div class="w-full">
            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="file_input">Event Brochure/Invitiation/label>
            <input required accept=".jpg,.png,.PNG,.JPEG" data-reason="activity_brochure" class="file block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none" aria-describedby="file_input_help" id="file_input" type="file">
            <p class="mt-1 text-sm text-gray-500" id="file_input_help">PNG, JPG(5 MB * 1 Photo)</p>
        </div>
    </div>
</div> -->
{% if activity.activity_name == "Project Completion" %}
    <div class="col-span-full">
            <div class="mb-2 flex justify-between items-center">
                <p class="font-semibold text-lg">Integrate Github</p>
                <a class="gap-2 inline-flex items-center justify-center font-semibold text-[#c09711] hover:text-[#C2A34E] hover:underline transition-colors duration-200">
                    Integrate
                    <img src="{% static 'images/chevron.svg' %}" alt="" class="w-5 h-5">
                </a>
            </div>
            <div class="flex items-center justify-center rounded-lg border-2 border-dashed border-gray-300 bg-white p-12 text-center">
                <div>
                    <div class="mx-auto h-12 w-12 text-gray-400">
                        <img src="{% static 'images/github.svg' %}" alt="" class="w-full opacity-55">
                    </div>
                    <h3 class="mt-2 text-2xl font-semibold text-gray-400">Coming Soon</h3>
                    <p class="mt-1 text-base text-gray-500">Student can integrate their github if available, it will be used for verification based on activity/commit/pull logs</p>
                </div>
            </div>
         </div>
{% endif %}
<div class="w-full h-[1px] bg-gray-200 col-span-full"></div>
 <!-- <div class="mb-4">
                            <label class="block text-base font-medium text-gray-800 mb-2">Selected Tags</label>
                            <div id="selected-tags" class="flex flex-wrap gap-2 min-h-[40px] p-3 border border-gray-300 rounded-lg bg-gray-50">
                                <span class="text-gray-500 text-sm" id="no-tags-message">No tags selected</span>
                            </div>
                        </div> -->
                        
                        <!-- Available Tags -->
                        <!-- <div class="mb-4">
                            <label class="block text-base font-medium text-gray-800 mb-2">Available Tags</label>
                            <div id="available-tags" class="flex flex-wrap gap-2 p-3 border border-gray-300 rounded-lg bg-white max-h-48 overflow-y-auto">
                                {% for tag in tags %}
                                <button type="button" 
                                        class="tag-button px-3 py-1 text-sm font-medium rounded-full border transition-all duration-200 hover:shadow-md"
                                        data-skill-id="{{ tag.id }}"
                                        data-skill-name="{{ tag.tag_name }}">
                                    {{ tag.tag_name }}
                                </button>
                                {% endfor %}
                            </div>
                        </div>
                        
                        Add New Tag
                        <div class="mb-4 col-span-full">
                            <label class="block text-base font-medium text-gray-800 mb-2">Add New Tag</label>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
                                <div>
                                <input type="text" 
                                       id="new-tag-input" 
                                       placeholder="Enter new tag name"
                                       class="flex w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D4AF37] focus:border-[#D4AF37]">
                                </div>
                                <div class="flex w-full gap-2">
                                <select class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 flex w-full appearance-none leading-normal text-gray-700" name="domain" id="id_domain"> 
                                    <option value="" selected disabled>---------</option> 
                                    {% for domain in domains %}
                                    <option value="1">{{domain.domain_name}}</option> 
                                    {% endfor %}
                                </select>
                                <button type="button" 
                                        id="add-new-tag-btn"
                                        class="px-4 py-2 bg-[#D4AF37] hover:bg-[#C2A34E] text-black font-medium rounded-lg transition-colors duration-200">
                                    Add
                                </button>
                                </div>
                            </div>
                            <small id="id_organizer_name_helptext" class="text-gray-600">Adding relevant tags helps us identify your achievements easily for ranking</small>
                        </div> -->

<div class="relative flex gap-x-3 col-span-full">
<div class="flex h-6 items-center">
    <input required id="comments" name="comments" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-[#D4AF37] focus:ring-[#D4AF37]">
</div>

<div class="text-sm leading-6">
    <p class="text-gray-800 font-semibold text-sm">I certify that the information I have provided in this form is true, complete, and accurate to the best of my knowledge.</p>
</div>
</div>

<button type="submit" class="col-span-full gap-2 flex items-center justify-center w-full px-4 py-3 rounded-lg font-medium text-black bg-[#D4AF37] hover:bg-[#C2A34E] shadow transition-colors duration-200">
    Submit for Attestation
    <img src="{% static 'images/check.svg' %}" alt="" class="w-5 h-5">
</button>
</form>
</div>
{% endblock %}

{% block script %}
<!-- <script src="{% static 'js/tags.js' %}"></script> -->
{% endblock %}

activity/templates/activity/base.html
{% load static %}
{% load static tailwind_tags %}
{% load tailwind_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <title>CPSAM | {% block title %} {% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css" rel="stylesheet" />
    {% tailwind_css %}
</head>
<body class="max-w-[1440px] mx-auto font-poppins">
    {% include "core/nav.html" %}
    {% block content %}

    {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

{% block script %}
{% endblock %}
</body>
</html>